# Generated by Django 2.2.6 on 2019-10-29 16:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest', '0002_albun_files'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Albun',
            new_name='Album',
        ),
    ]
